####### resource server configuration properties
# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://localhost:8083/auth/realms/ates
#           jwk-set-uri: http://localhost:8083/auth/realms/ates/protocol/openid-connect/certs

kafka:
  bootstrapAddress: localhost:29092