server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: ates-realm.json
