spring:
  application:
    name: auth

server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"