spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ates-client
            client-secret: ssoClientSecret-1
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/ates/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/ates/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/ates/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet: 
    context-path: /ui
    
logging: 
  level: 
    org.springframework: INFO
    com.github.poserg.ates: DEBUG

task-tracker-service:
  api:
    url: http://localhost:8081/task-tracker-service/api/tasks/

