server: 
  port: 8081
  servlet: 
    context-path: /task-tracker-service

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/ates
          jwk-set-uri: http://localhost:8083/auth/realms/ates/protocol/openid-connect/certs

logging:
    level:
        com.github.poserg.ates: DEBUG